CREATE SEQUENCE seq_users
  MINVALUE 1
  MAXVALUE 10000
  START WITH 1
  INCREMENT BY 1;
  
  --CREATE GAME
CREATE SEQUENCE seq_game
  MINVALUE 1
  MAXVALUE 100
  START WITH 1
  INCREMENT BY 1;
  
  --CREATE GAME PLAYER
CREATE SEQUENCE seq_game_player
  MINVALUE 1
  MAXVALUE 10000
  START WITH 1
  INCREMENT BY 1;
  
  --DRAWN CARD HISTORY
DROP SEQUENCE seq_drawn_cards

CREATE SEQUENCE seq_drawn_cards
  MINVALUE 1
  MAXVALUE 10000
  START WITH 1
  INCREMENT BY 1;
  